"""add vector embedding 384

Revision ID: 09410f09da2b
Revises: 8ab2ebafe39f
Create Date: 2026-04-26 21:23:09.035423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '09410f09da2b'
down_revision: Union[str, Sequence[str], None] = '8ab2ebafe39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('embedding', Vector(384), nullable=True))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    # ### end Alembic commands ###
